name: run tests

on:
  pull_request:
    branches: [master]

jobs:
  test-ml-client:
    name: ML client (python 3.10)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./machine-learning-client
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pipenv"

      - name: install pipenv
        run: pip install pipenv

      - name: install dependencies
        run: pipenv install --dev --deploy

      - name: run pytest
        run: pipenv run pytest tests/*

  test-web-app:
    name: web app (python 3.10)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-app
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pipenv"

      - name: install pipenv
        run: pip install pipenv

      - name: install dependencies
        run: pipenv install --dev --deploy

      - name: run pytest
        run: pipenv run pytest tests/*
